### PR TITLE
Quartz Rebrand

### LINKED ISSUE #362: Update to Quartz
## Detailed Description
We want to update to quartz solar

## Context
- update to quart solar for 5th June
- Want to make sure nowcasting still works, and later turn it off

## Possible Implementation
- [ ] add `app.quartz.solar` UI on cloudfalre, also add for `development` and `staging`
- [ ] Auth0 allow new UI callbacks
- [ ] change logs on nowcasting app
- [ ] Change logo on Notion Docs
- [ ] Change logos on api

Later on
- [ ] remove app.nowcasting.io

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Update logo and branding to match new Quartz name/style.

Fixes #362

## How Has This Been Tested?

Tested on Vercel staging preview deployment

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

# Pull Request

## Description

Update logo and branding to match new Quartz name/style.

Fixes #362

## How Has This Been Tested?

Merged to `staging` for final manual testing on Vercel staging preview deployment

- [x] Yes

# UAT

## Quartz-specific points
- [x] Does the logo look like the new Quartz logo?
- [x] Does the logo link to the new Quartz website?
- [x] Is the OCF logo present in the logo area?
- [x] Does the OCF logo link to the OCF website?
- [x] Does the Documentation link go to the new Quartz docs?

### National
- [x] Does PV live estimate show on the plot? (black dashed)
- [x] Does PV live updated show on the plot? (black solid)
- [x] Does OCF forecast show up on plot? (yellow)
- [x] For OCF forecast, is the future a dashed line?
- [x] Can I hover on the plot to show the values on the plot?
- [x] Does the data look like solar profiles?
- [x] Clicking on a GSP makes the GSP plot show up?
- [x] Clicking on a GSP when already selected, makes the GSP plot go away?
- [x] Can I click on a time in the national plot which then updates the map?
- [x] Can I click on a time in the GSP plot which then updates the map?
- [x] Are values higher on the map in the middle of the day, compared to early morning?

#### Time
- [x] Is time now in Europe London time? It should be to the nearest 30 minute, rounded up.
- [x] Is the hover time in Europe London time?
- [x] Are the X axis in Europe London time?
- [x] Does the data show yesterday as well?
- [x] Does the data show tomorrow as well?

#### Header
- [x] Is this the title clear it is National data?
- [x] Does the headline current estimated PV figure display?
- [x] Does it show the current Forecasted value?
- [x] Does the next forecast figure display?
- [x] Are the units GW?

### GSP
- [x] Does PV live estimate show on the plot? (dashed black)
- [x] Does PV live updated show on the plot? (solid black)
- [x] Does OCF forecast show up on plot? (yellow)
- [x] For OCF forecast, is the future a dashed line?
- [x] Can I hover on the plot to show the values on the plot?
- [x] Does the data look like solar profiles?

#### Time
- [x] Is time now in Europe London time?
- [x] Is the hover time in Europe London time?
- [x] Are the X axis in Europe London time?

#### Title
- [x] Does the GSP name show up?
- [x] Is the current estimated PV visible?
- [x] Is the next forecast figure visible?
- [x] Are the above figures in MW?
- [ ] Does the current percentage yield figure display? [no longer shown]
- [ ] Is the installed capacity visible? [no longer shown]

###  Map
- [x] Does a map of the UK show up?
- [x] Are the GSP boundaries displayed?
- [x] Can I click on '%', 'MW' and 'Capacity'
- [x] on 'Capacity' view, is there very little power in Scotland, and Melksham a shining beacon of renewables?

### National
- [x] Does the "4hr forecast" toggle show in the Profile Dropdown menu?
- Toggle on
  - [x] Does the 4hr forecast show up on the plot? (orange)
  - [x] Does the 4hr future forecast show up on the plot? (dashed orange)
  - [x] Does the 4hr forecast _not_ show on the chart or tooltip when switched off?
- Toggle off
  - [x] Does the 4hr forecast _not_ show on the chart or tooltip when switched off?
  - [x] Does the 4hr future forecast _not_ show on the chart or tooltip when switched off?
- [x] Does the 4hr forecast toggle persist across refreshes/logouts using cookie?
- [x] Do the 4hr forecast values show in the hover tooltip?

### National
- [x] Does PV live estimate show on the plot? (black dashed)
- [x] Does PV live updated show on the plot? (black solid)
- [x] Does OCF forecast show up on plot? (yellow)
- [x] For OCF forecast, is the future a dashed line?
- [x] Does the 4-hour forecast _not_ show on the chart or tooltip when switched off?
- [x] Does the 4-hour future forecast _not_ show on the chart or tooltip when switched off?
- [x] Does the 4-hour forecast show on the chart and tooltip when switched on?
- [x] Can I hover on the plot to show the values on the plot?
- [x] Does the data look like solar profiles?
- [x] Clicking on a GSP makes the GSP plot show up?
- [x] Clicking on a GSP when already selected, makes the GSP plot go away?
- [x] Can I click on a time in the national plot which then updates the map?
- [x] Can I click on a time in the GSP plot which then updates the map?
- [x] Are values higher on the map in the middle of the day, compare to early morning?

#### Time
- [x] Is time now in Europe London time? It should be 30minute, but rounded up.
- [x] Is the hover time in Europe London time?
- [x] Are the X axis in Europe London time?
- [x] Does the data show yesterday as well?

#### Header
- [x] Is this the title clear it is National data?
- [x] Does the headline current estimated PV figure display?
- [x] Does it show the current Forecasted value?
- [x] Does the next forecast figure display?
- [x] Are the units GW?

### GSP
- [x] Does PV live estimate show on the plot? (dashed black)
- [x] Does PV live updated show on the plot? (solid black)
- [x] Does OCF forecast show up on plot? (yellow)
- [x] For OCF forecast, is the future a dashed line?
- [x] Can I hover on the plot to show the values on the plot?
- [x] Does the data look like solar profiles?

#### Time
- [x] Is time now in Europe London time?
- [x] Is the hover time in Europe London time?
- [x] Are the X axis in Europe London time?

#### Title
- [x] Does the GSP name show up?
- [x] Is the latest forecast figure visible?
- [ ] Is the next forecast figure visible? [not currently shown for space reasons]
- [x] Is the current GSP delta figure visible?
- [x] Are the above figures in MW?
- [x] Is the Delta block background colour correct, i.e. pos/neg delta colour scheme?

###  Map
- [x] Does a map of the UK show up?
- [x] Are the GSP boundaries displayed?
- [x] Where Deltas are available, do the correct colours for the GSP delta buckets display and match the table?

## Combined views
- [x] Does **selectedGSP** persist when switching between `PV Forecast` and `Delta` Views
- [x] Does **selectedTime** persist when switching between `PV Forecast` and `Delta` Views
- [x] Does **map location/zoom** persist when switching between `PV Forecast` and `Delta` Views

## Dashboard Mode

- [x] Does the `Dashboard Mode` toggle show in the Profile Dropdown menu?
- [x] Does the `Dashboard Mode` toggle persist across refreshes/logouts using cookie?

### National
- [x] Do the `National` title and forecast values show in large font?
- [x] Are the lines on the chart thicker?

### GSP
- [x] Do the `GSP` title and forecast values show in large font?
- [x] Are the lines on the chart thicker?

### Legend
- [x] Is the legend larger?
- [x] Do the legend items space nicely?

### Map
- [x] Is the map legend larger?
- [x] Are the MW/%/Capacity buttons larger?
- [x] Are the date/time larger?

## General
- [x] is the version visible?
- [x] has the version been bumped?
- [x] Does the feedback button work?
- [x] Is the legend visible
- [x] Is the database stable, check on AWS

### Auth
- [x] Can I log on with Auth?
- [x] Can i log out?

### Refresh
- [x] After 10 mins, does the forecast update?
- [x] After 10 mins, does the forecast creation time update?

### Documentation
- [x] Update documentation - https://openclimatefix.notion.site/Quartz-Solar-Documentation-0d718915650e4f098470d695aa3494bf
- [x] Do we need to email the users - Yes, Monday 17th July possibly is the plan - @dantravers @peterdudfield ?

### CODE REVIEW

**Comment by peterdudfield** [comment]
would you be able to do the full QA?

**Comment by braddf** [comment]
Will do first thing Wednesday morning @peterdudfield 👍 unless @rachel-labri-tipton fancies running through the UAT in my absence tomorrow - but I would not blame anyone for not jumping to do it... 😂

**Comment by rachel-labri-tipton** [comment]
hey @peterdudfield and @braddf, I'd be willing to walk through the QAT today as a pre-flight check to flag anything before @braddf does the final sign off tomorrow. Is the checklist just the list in the original issue #362?

**Comment by braddf** [comment]
oh good point @rachel-labri-tipton - I had forgotten there was that list on the issue also, definitely that one needs "checking off", but I was thinking of the full UAT thing we use on releases usually, a la [Dashboard Mode PR](https://github.com/openclimatefix/nowcasting/pull/364) for reference - is that what you meant as well @peterdudfield or..?

**Comment by braddf** [comment]
@rachel-labri-tipton @peterdudfield have just done the UAT and all looks good! Fixed a couple of bits, some of which were actually broken/missing for a long time before (maybe pre-Brad tbh haha) 

Permission to merge? 🙏

**Pull request merged**
