### PR TITLE
Init pre-commit eslint/prettier setup & fix errors

### LINKED ISSUE #210: Add linting & prettier as pre-commit

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Finish setup of `pre-commit` and configure to run `eslint` and `prettier` before each commit.

Closes #210 

## How Has This Been Tested?

Threw up a good few errors, almost all of which were fixed automatically by `eslint --fix` as part of the `pre-commit` hook.

UPDATE: `pre-commit` package is definitely less used for JS/node stuff, so removed from this repo and replaced with:
- Existing Vercel hooks/build runs full ESLint/prettier checks and fails the build of the Preview branches on Errors (not Warnings, those are okay)
- Added [Husky](https://typicode.github.io/husky/#/) and [lint-staged](https://github.com/okonet/lint-staged) for the pre-commit hook functionality on local side; should prevent commit if linting fails, no build step here as on balance I think it takes too long. Maybe can consider this as a final check on `git push` later on.

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Im not sure why, but the pre-commit.ci seem to bring up an error about babel - `  0:0  error  Parsing error: Cannot find module 'next/babel'`

**Comment by peterdudfield** [comment]
do you know what the error for rendering 404 page is about?

**Comment by braddf** [comment]
@peterdudfield @rachel-labri-tipton btw this should be good to go/review now! Amended description 👍

**Review by peterdudfield — COMMENTED** [review]
well done - looks great!

**Review by peterdudfield — APPROVED** [review]

**Comment by peterdudfield** [comment]
if possible could you put this PR in the project WP3 in September iteration? That just helps us keep track of a few thigns

**Pull request merged**
