### PR TITLE
e2e tests

### LINKED ISSUE #28: selenium Tests

### LINKED ISSUE #145: Testing/ complete dummy api for testing

### LINKED ISSUE #146: Testing/ setup cypress test with auth0 (preferably bypass auth0 with no login)

### LINKED ISSUE #147: Testing/ write test scenarios and implement tests

### LINKED ISSUE #148: Testing/ trigger cypress on updates

### LINKED ISSUE #149: Testing/ write unit test for helper functions

### PR DESCRIPTION
**Pull request by dlinah**
# Pull Request

main pr for testing stories

main story: 
Fixes #28

sub stories: 
Fixes #145, Fixes #146, Fixes #147, Fixes #148

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Sorry about the conflicts, hoepfully you can sort them. Please get @dctanner to review this soon ish, so we can avoid further branch conflcts

**Comment by dctanner** [comment]
> Sorry about the conflicts, hoepfully you can sort them. Please get @dctanner to review this soon ish, so we can avoid further branch conflcts

I'm on holiday for another 2.5w so might be best to go ahead without me.

**Comment by peterdudfield** [comment]
> > Sorry about the conflicts, hoepfully you can sort them. Please get @dctanner to review this soon ish, so we can avoid further branch conflcts
> 
> I'm on holiday for another 2.5w so might be best to go ahead without me.

@dlinah you ok to sort the conflicts and then we can merge. @dctanner can review this after the holiday. Sound ok?

**Comment by dlinah** [comment]
@dlinah

**Comment by dctanner** [comment]
Looking good Linah. I've been able to do a brief review, but I've asked @Alaatohamy to do a more in depth review because she has more context to review the actual code.

**Comment by dlinah** [comment]
@Alaatohamy lmk if you wanna do a pair review

**Comment by Alaatohamy** [comment]
> @Alaatohamy lmk if you wanna do a pair review

sure do you want to pair now ?

**Pull request closed without merging**
