### PR TITLE
Test removing unneeded api calls

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Fixes #

## How Has This Been Tested?

Preview branch here: https://nowcasting-aas1wfc74-openclimatefix.vercel.app/

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Sorry @braddf I didnt look at this. This is probably worth doing. Do you mind looking at the merge conflicts? There's a chance this has been done already on `staging`, if so, shall we close this?

**Comment by peterdudfield** [comment]
Perhaps @braddf we can close this now? has the work been done in a different branch?

**Comment by braddf** [comment]
@peterdudfield – I'm not sure it all has actually, it may have, and I think @rachel-labri-tipton's PR to remove the GSP All API call was maybe some of this, and other stuff here may have been refactored and is outdated now, but I'll double check and either update or close this PR 👍

**Comment by peterdudfield** [comment]
> @peterdudfield – I'm not sure it all has actually, it may have, and I think @rachel-labri-tipton's PR to remove the GSP All API call was maybe some of this, and other stuff here may have been refactored and is outdated now, but I'll double check and either update or close this PR 👍

Not sure this helps, but here are all the URL calls from the UI in the last 5 mins (I think from the UI)
Screenshot 2023-08-10 at 11 39 17

**Comment by braddf** [comment]
Ah grand, from the looks of that we should be okay then; I'll be going through all of this at least once as we make these speed upgrades so happy for this PR to be closed

**Comment by peterdudfield** [comment]
now out of date?

**Comment by braddf** [comment]
Closing, think has been merged elsewhere and now out-of-date

**Pull request closed without merging**
