### PR TITLE
Issue/365 loading states

### LINKED ISSUE #365: Improve loading states/feedback in UI
## Detailed Description
Provide more granular loading states and messages in the app to tell the user (and us) what is currently loading, and if anything specific has failed to load.

## Context
Right now, we have mostly just general spinners that hide the main chart components when the data is loading - this includes both first load, and currently also when data is being refetched (which is potentially jarring and frustrating as a user, I would personally rather see the current, existing data in the cache, even if slightly "stale", rather than no data and a spinner.

## Possible Implementation
- Finish implementing a "skeleton view" of all charts, so they can load and render as empty before the data has loaded in;
- Ensure the loading states of various API calls are kept in separate variables, and potentially use each of these to inform a state machine to determine the App's current state of loading; some data will be similar/related, so can share the same `Loading Message`, and these messages can represent discrete states of the currently loaded App data. 

- An example of these states could be:
  - **PV Forecast and Delta views specific**
  - `Loading data...` [no data has fully loaded yet / multiple data requests active and have state of loading]
  - `Loading Forecast data...` [PV actuals have loaded, forecasts are pending]
  - `Loading PV data...` [forecasts have loaded, PV actuals are pending]
  - `Loading GSP data...` [National data loaded, GSP data request pending]
  - `Refreshing data...` [existing data for PV and Forecasts, both API calls pending/loading]
  - `Refreshing Forecast data...` [existing data for PV and Forecasts, only Forecast API call pending]
  - `Refreshing PV data...` [existing data for PV and Forecasts, only PV data call pending]
  -  **Sites view specific**
  - `Loading Sites...` [getSites request loading]
  - `Loading Sites Forecast data...` [sites PV data loaded, sites forecasts pending]
  - `Loading Sites PV data...` [sites forecast data loaded, PV data pending]

>N.B. This refactoring could also give easy opportunity to record which API calls are failing and when

&nbsp;

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Add some loading states, similar to those suggested in the below issue. Not from designs, so testing and feedback welcome!

- On initial load, and therefore when no data has been loaded yet, the skeleton graph displays the main spinner.
- Data in the app is now "de-duped", so the same API route will not be requested with the same parameters if the latest response is **less than 2 minutes old**.
- On 'refresh' of the data, which happens either from the 5 minute background timer having elapsed, or from a user interaction e.g. with the charts _after_ the 2 minute 'de-dupe' timeout having elapsed, the API requests are re-fetched and the loading message appears.
  - If more than one request is currently pending, "Loading latest data" is displayed;
  - If only one request is pending, the message specifies this, e.g. "Loading latest GSP forecast" – this one shows more often, because at the moment it is large/slow, and called perhaps more often than needed, as @rachel-labri-tipton, @devsjc and I have been discussing recently. I notice from the screenshot below that the message is also perhaps a bit long, so might want shortening.

Fixes #365 

## How Has This Been Tested?

Locally, forcing API to update every 30 seconds and also manually triggering updates to different API endpoints to check messages.

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

## Screenshots of example loading messages:

image

image

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks @braddf for doing this. I've had a look on the preview vercel site but I couldnt see any loading states. 

Perhaps they are not meant to be visible? If so where are they? and is it just for us internally to use? 
If not, could add a few screen shot to the PR of these features? 

Thanks

**Comment by braddf** [comment]
@peterdudfield have amended description, hopefully should be clearer before and I can see why you may not have seen it in the Preview deploy! Have to have the tab open and check back in after 2 mins to see it in the wild – this might not be how we want it, open to discussion! 👍

**Comment by peterdudfield** [comment]
> @peterdudfield have amended description, hopefully should be clearer before and I can see why you may not have seen it in the Preview deploy! Have to have the tab open and check back in after 2 mins to see it in the wild – this might not be how we want it, open to discussion! 👍

Thanks @braddf , I now see them.

I think they are useful and handy and give some nice user feedback. How do you feel about the design of them?

**Comment by braddf** [comment]
I feel like is a good v1 - I don't like designing in a vacuum so keen to get them onto `development` etc. to get prompt some feedback but they seem to be doing what I hoped they would, and show promise for further feature expansion I think? 👍

**Review by peterdudfield — APPROVED** [review]

**Pull request merged**
