### PR TITLE
Hotfix/399 style not loaded bug

### LINKED ISSUE #399: Style is not loaded - Mapbox
## Describe the bug
Error when loading Quartz UI – if the map has not fully loaded, in particular the internal Style class of the visible mapbox instance, and the data loads in, the app with attempt to apply the data to the map layer styling, resulting in an error. 

## To Reproduce
1. On refresh, especially if data is cached and returned quickly, sometimes the UI will return this error

## Expected behavior
No error 😅

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Add wrapper function util for map update functions to prevent not loaded error(s).

Fixes #399 

## How Has This Been Tested?

Tested locally and loads data fine on 10 fast refreshes with cached API data

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
This looks a huge amount of chagnes fro a hotfix?

**Comment by braddf** [comment]
> This looks a huge amount of chagnes fro a hotfix?

@peterdudfield Yep this was the [Draft] necessity 😄 branched off of `development` by accident rather than `staging` – should be updated now so just waiting for Preview deploy 👍

**Review by peterdudfield — CHANGES_REQUESTED** [review]
Dont merge -

The gGSP are in the wrong locations

**Comment by peterdudfield** [comment]
Screenshot 2023-08-15 at 11 52 39

The gsps seems to be in the wrong place? Could this be a gsp_id has been shifted and is not right? I dont know

**Review by peterdudfield — APPROVED** [review]
gsp mismatch is in dev api

**Pull request merged**
